apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  namespace: production
  labels:
    app: content-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: ghcr.io/stefanprodan/podinfo:6.11.0
        ports:
        - containerPort: 9898
          name: http
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: PODINFO_UI_MESSAGE
          value: "content-api (StreamFlix)"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: content-api
  namespace: production
spec:
  selector:
    app: content-api
  ports:
  - port: 9898
    targetPort: 9898
    name: http
