apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: streamflix-services
  namespace: production
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - content-api
      - recommendation-api
      - player-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
