{
 "title": "Site Kubectl — SLO Dashboard",
 "tags": [
  "reliabilitylab",
  "slo",
  "sre",
  "error-budget"
 ],
 "panels": [
  {
   "title": "Disponibilidade Atual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace='reliabilitylab',status!~'5..'}[30m])) / sum(rate(http_requests_total{namespace='reliabilitylab'}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Error Budget Consumido",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "clamp_max(((1 - (sum(rate(http_requests_total{namespace='reliabilitylab',status!~'5..'}[1h])) / sum(rate(http_requests_total{namespace='reliabilitylab'}[1h])))) / (1 - 0.999)) * 100, 100)"
    }
   ]
  },
  {
   "title": "Burn Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{namespace='reliabilitylab',status!~'5..'}[1h])) / sum(rate(http_requests_total{namespace='reliabilitylab'}[1h])))) / (1 - 0.999)"
    }
   ]
  },
  {
   "title": "Latência P95",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace='reliabilitylab'}[5m])) by (le))"
    }
   ]
  }
 ]
}