apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: player-api-availability
  namespace: monitoring
spec:
  service: "player-api"
  slos:
  - name: "requests-availability"
    objective: 99.9
    description: "player-api deve estar disponível 99.9% do tempo"
    sli:
      events:
        errorQuery: sum(rate(http_request_duration_seconds_count{job="player-api",status=~"5.."}[{{.window}}]))
        totalQuery: sum(rate(http_request_duration_seconds_count{job="player-api"}[{{.window}}]))
    alerting:
      name: "PlayerApiHighErrorRate"
      labels:
        category: "availability"
      pageAlert:
        labels:
          severity: "critical"
      ticketAlert:
        labels:
          severity: "warning"
