grafana:
  adminPassword: "admin123"
  service:
    type: NodePort
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        folder: ReliabilityLab
        type: file
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      kubernetes-overview:
        gnetId: 15661
        revision: 2
        datasource: Prometheus
      hpa-scaling:
        gnetId: 10257
        revision: 1
        datasource: Prometheus

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    storage: {}
